### ISSUE TITLE
斗鱼的链接隔天会变

### ISSUE THREAD

**Issue by willie91** [wbt5/real-url#100]
作者你好
这个id4926715我第一次生成是下面这个链接
http://tx2play1.douyucdn.cn/live/4926715rgZLvX3Z3.flv?uuid=
然后我隔天发现失效了，我重新生成，这次的链接是
http://tx2play1.douyucdn.cn/live/4926715rjwZ3SEoJ.flv?uuid=
但是奇怪的是，斗鱼的王者荣耀和英雄联盟官方直播间生成的链接还是可以正常用的

**Comment by wbt5** [comment]
@willie91 每次下播后开播，链接都是会变的。

**Comment by willie91** [comment]
> @ willie91每次下播后开播，链接都是会变的。

这样啊- -.那获取真实的直播源好像用处就不大了呀.

**Comment by wbt5** [comment]
@willie91 有些获取链接是为了录像或本地播放
