### ISSUE TITLE
执行douyu.py会导致cpu飙升至100%

### ISSUE THREAD

**Issue by xiaoshuaishuai** [wbt5/real-url#103]
top
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3672327 root      20   0   10.5g 109748  16960 S 336.8   0.3   0:03.61 jjs
3672348 root      20   0   10.5g  62816  17028 S 163.2   0.2   0:01.79 jjs
3672369 root      20   0   10.5g  49304  16884 S 121.1   0.2   0:00.96 jjs
3672391 root      20   0   10.5g  33612  16124 S 121.1   0.1   0:00.28 jjs

 ps aux|grep jjs
root     3672851  131  0.2 11234900 81640 ?      Sl   16:53   0:02 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsmh9l8gc5.js
root     3672872 64.0  0.1 11033092 58844 ?      Sl   16:53   0:01 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsnk7282r_.js
root     3672889  119  0.1 11033092 58064 ?      Sl   16:54   0:01 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsew1abbjg.js
root     3672914 45.0  0.1 11031044 38828 ?      Sl   16:54   0:00 /opt/jdk1.8.0_261/bin/jjs /tmp/execjs8f5k_72j.js
root     3672930 31.0  0.1 11030560 34840 ?      Sl   16:54   0:00 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsbxlvciml.js

请问作者这个是因为douyu.py 有引用execjs 还是正则需要优化呢？ 我把这个斗鱼停止cpu会降下来
top  停止之后

%Cpu(s):  0.7 us,  0.1 sy,  0.0 ni, 99.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  31595.7 total,  15290.8 free,   6583.1 used,   9721.7 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  24567.8 avail Mem

启动之后
 ps aux|grep jjs
root     3684958 79.3  0.3 11236948 128872 pts/2 Sl   16:59   0:04 /opt/jdk1.8.0_261/bin/jjs /tmp/execjs1ezp61zs.js
root     3685005 80.4  0.3 11234900 106600 pts/2 Sl   16:59   0:04 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsnbf3x8fm.js
root     3685008 90.2  0.2 11234900 96020 pts/2  Sl   16:59   0:03 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsjuw_o4jn.js
root     3685051 39.6  0.1 11031044 55664 pts/2  Sl   16:59   0:01 /opt/jdk1.8.0_261/bin/jjs /tmp/execjs4r8bw6x_.js
root     3685052 36.0  0.1 11031044 52452 pts/2  Sl   16:59   0:01 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsi2nytp02.js
root     3685094 39.5  0.1 11031044 44680 pts/2  Sl   16:59   0:00 /opt/jdk1.8.0_261/bin/jjs /tmp/execjss9_vvp3r.js
root     3685122 27.0  0.1 11030560 33216 pts/2  Sl   16:59   0:00 /opt/jdk1.8.0_261/bin/jjs /tmp/execjs_q5pv1ms.js
root     3685125 23.0  0.1 11030560 33324 pts/2  Sl   16:59   0:00 /opt/jdk1.8.0_261/bin/jjs /tmp/execjsanc5mylq.js
root     3685159  5.0  0.0 10757892 21908 pts/2  Sl   16:59   0:00 /opt/jdk1.8.0_261/bin/jjs /tmp/execjst9324l7g.js

没有看明白 为什么会执行到java的jjs指令

**Comment by xiaoshuaishuai** [comment]
是因为我的服务器没有安装node吗？ 服务器装了Java环境，java的jjs是执行js的引擎。然后py execjs执行的时候找到了jjs去执行了。

**Comment by xiaoshuaishuai** [comment]
Java 8 Nashorn JavaScript Java 8 新特性 Nashorn 一个 javascript 引擎

执行测试 execjs.get().name

输出 Nashorn

果然调用了java的js引擎

源码中给出， 可执行execjs的环境：
  PyV8           = "PyV8"
  Node           = "Node"
  JavaScriptCore = "JavaScriptCore"
  SpiderMonkey   = "SpiderMonkey"
  JScript        = "JScript"
  PhantomJS      = "PhantomJS"
  SlimerJS       = "SlimerJS"
  Nashorn        = "Nashorn"

**Comment by xiaoshuaishuai** [comment]
换成node cpu降下来了

**Comment by wbt5** [comment]
@xiaoshuaishuai 老哥正解，使用nodejs即可
