### ISSUE TITLE
接口的确认方式

### ISSUE THREAD

**Issue by y4127241990** [wbt5/real-url#108]
抖音的请求接口：            room_url = 'https://webcast-hl.amemv.com/webcast/room/reflow/info/?room_id={}&live_id=1'.format(room_id)

哔哩哔哩请求接口：r_url = 'https://api.live.bilibili.com/room/v1/Room/room_init?id={}'.format(self.rid)

我想问下这个接口是怎么确定就是这些的，您能提供下视频或者是什么方法嘛，我想学习下怎么去做

**Comment by y4127241990** [comment]
close

**Comment by wbt5** [comment]
打开直播间，F12 开启浏览器调试即可。
