### ISSUE TITLE
增加youtube的直播地址获取，你可以整理到代码中

### ISSUE THREAD

**Issue by y4127241990** [wbt5/real-url#109]
from pafy import pafy

class YouTube:

    def __init__(self, rid):
        self.rid = rid

    def get_real_url(self):
        # https://www.youtube.com/watch?v=bwjhikkGjPU
        url = 'https://www.youtube.com/watch?v={}'.format(str(self.rid))
        video = pafy.new(url)
        if video:
            print(video)
            print(video.getbest().url)
            print(video.author)
            print(video.title)

def get_real_url(rid):
    try:
        yt = YouTube(rid)
        return yt.get_real_url()
    except Exception as e:
        message = '系统异常信息：{}'.format(e)
        return message

if __name__ == '__main__':
    # r = input('请输入Youtube直播房间号：\n')
    r = 'bwjhikkGjPU'
    print(get_real_url(r))

**Comment by wbt5** [comment]
感谢！

**Comment by y4127241990** [comment]
关闭
