### ISSUE TITLE
运行danmu/main.py闪退

### ISSUE THREAD

**Issue by LukeJean** [wbt5/real-url#117]
还没有输入直播间地址就闪退了，asyncio包已经装了

**Comment by LukeJean** [comment]
解决了，原来用的`python3 main.py`，后来改成`python main.py`就好了。
另外说一下在获取快手弹幕中遇到的坑。
报错`找不到 wsFeedInfo，可能链接错误或 Cookie 过期`，把`/danmu/danmaku/kuaishou.py`的第30行的did换成快手直播Application的Cookies中的did，换了Cookie之后，还是报`找不到 wsFeedInfo，可能链接错误或 Cookie 过期`，那可能是链接不对，注释掉`/danmu/danmaku/kuaishou.py`的第25行26行，输链接时直接输网页版快手直播的链接。

**Comment by qiqiJiang-st** [comment]
请问你注释掉那两句就好使了吗？我仍然不好使，打印了一下返回的res，发现找不到wsFeedInfo这个键。

**Comment by LukeJean** [comment]
> 请问你注释掉那两句就好使了吗？我仍然不好使，打印了一下返回的res，发现找不到wsFeedInfo这个键。

刚开始还好使来着，过了一个礼拜之后换了好几个did也没用

**Comment by qiqiJiang-st** [comment]
> > 请问你注释掉那两句就好使了吗？我仍然不好使，打印了一下返回的res，发现找不到wsFeedInfo这个键。
> 
> 刚开始还好使来着，过了一个礼拜之后换了好几个did也没用
看来应该是快手做了更新，现在快手弹幕这个爬虫已经失效了，我已经请求博主更新了，希望能早点更新吧。

**Comment by LukeJean** [comment]
> > > 请问你注释掉那两句就好使了吗？我仍然不好使，打印了一下返回的res，发现找不到wsFeedInfo这个键。
> > 
> > 
> > 刚开始还好使来着，过了一个礼拜之后换了好几个did也没用
> > 看来应该是快手做了更新，现在快手弹幕这个爬虫已经失效了，我已经请求博主更新了，希望能早点更新吧。

我们公司最近正好有这个需求，实在不行只能自个儿上手搞了

**Comment by wbt5** [comment]
现在快手的有效 did 比较难直接获取，浏览器和模拟器新生成的无法直接使用，可能有个注册过程，具体需要反编译APP了。
如果有好的解决办法，欢迎告知。

**Comment by wbt5** [comment]
我测试用本地浏览器 cookie 里的 did，可以直接使用，但新获取的不行。
