### ISSUE TITLE
大佬，可以添加一个http://www.winktv.co.kr/直播源获取吗

### ISSUE THREAD

**Issue by lloyd18** [wbt5/real-url#12]

**Comment by wbt5** [comment]
这网站貌似打不开

**Comment by lloyd18** [comment]
> 这网站貌似打不开

要翻墙。

**Comment by youxia2016** [comment]
winktv使用websocket协议,而且需要登陆,https://github.com/youxia2016/WinkTvLiveRecorder,这里可以录制，已开源

**Comment by awaycloud** [comment]
> winktv使用websocket协议,而且需要登陆,[https://github.com/youxia2016/WinkTvLiveRecorder,这里可以录制，已开源](https://github.com/youxia2016/WinkTvLiveRecorder,%E8%BF%99%E9%87%8C%E5%8F%AF%E4%BB%A5%E5%BD%95%E5%88%B6%EF%BC%8C%E5%B7%B2%E5%BC%80%E6%BA%90)

404 请问能再发一下嘛  不方便公开也可以私发8001927#gmail.com（# = @）谢谢大佬
