### ISSUE TITLE
抖音无效，作者大大尽快修复

### ISSUE THREAD

**Issue by googlechn** [wbt5/real-url#129]
请输入抖音直播间room_id或分享链接：
6909400769310509831
Exception： 直播间不存在或未开播或参数错误
False

请输入抖音直播间room_id或分享链接：
https://v.douyin.com/Jboe4Rp/
Exception： 直播间不存在或未开播或参数错误
False

**Comment by SeaHOH** [comment]
你这标题欠妥，可否修改下？

**Comment by wbt5** [comment]
目前测试能正常获取。
注意，即使同一个主播，每次开播时的分享链接和 id 都会变化的。

**Comment by SeaHOH** [comment]
脾气真是好。先不说标题，单是如此明显的重复问题，直接关闭并链接过去就行了，你还规规矩矩的回复他。
