### ISSUE TITLE
虎牙、斗鱼、快手不能获取弹幕

### ISSUE THREAD

**Issue by wangyixu** [wbt5/real-url#137]
虎牙和斗鱼是 session.get(url, headers=headers) 回复404或者直播间不存在，快手替换cookie后还是 raise Exception('找不到 wsFeedInfo，可能链接错误或 Cookie 过期')。企鹅电竞有点小bug：o['position'] 可能是str；bin_data 没有 'type' 健。

辛苦大佬排查、更新下。

**Comment by wbt5** [comment]
虎牙和斗鱼正常
快手 Duplicate of #130
