### ISSUE TITLE
企鹅电竞弹幕获取一部分弹幕后报错

### ISSUE THREAD

**Issue by Frankyzzd** [wbt5/real-url#140]
获取一小部分弹幕后，就报错，我改了数据类型也不行，不知道哪里出问题了  还有希望能提供企鹅电竞弹幕获取的思路
![无标题](https://user-images.githubusercontent.com/39256508/105057315-1059da00-5ab0-11eb-9b5f-b89578f4714a.png)

**Comment by ziwen123450** [comment]
def S(self, e, t=0):
        if t == '':
            t = 0
        i = []
        n = len(e)
        while t < n:
            o = self.m(e, t)
            dict_ = {
                'value': o['value'],
                'lastPosition': o['position'],
                'ext': o['ext'],
                'tag': o['tag']
            }
            i.append(dict_.copy())
            t = o['position']
---------这里----------------
            if t == '':
                t = 0
-----------------------------------
        return i, e
我是修改了一下 可以获取了

**Comment by wbt5** [comment]
Duplicate of #209
