### ISSUE TITLE
获取虎牙的真实链接在拼接url时多了空格

### ISSUE THREAD

**Issue by xurk0922** [wbt5/real-url#143]
在https:与//之间多了个空格

{
	'2000p': 'https: //tx.hls.huya.com/src/78941969-2579769454-11080025436149776384-3144993630-10057-A-0-1-imgplus_2000.m3u8?wsSecret=49191e67b6ab7b5e9e4f78d69bee217d&wsTime=6017b49b&u=0&seqid=16120799213176012&ctype=tars_mobile&txyp=o%3Aq6%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&t=103',
	'tx': 'https: //tx.hls.huya.com/src/78941969-2579769454-11080025436149776384-3144993630-10057-A-0-1-imgplus.m3u8?wsSecret=9077810f34fe8d9b866ef5b9930bb232&wsTime=6017b49b&u=0&seqid=16120799213176012&ctype=tars_mobile&txyp=o%3Aq6%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&t=103',
	'bd': 'https: //bd.hls.huya.com/src/78941969-2579769454-11080025436149776384-3144993630-10057-A-0-1-imgplus.m3u8?wsSecret=9077810f34fe8d9b866ef5b9930bb232&wsTime=6017b49b&u=0&seqid=16120799213176012&ctype=tars_mobile&txyp=o%3Aq6%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&t=103',
	'migu-bd': 'https: //migu-bd.hls.huya.com/src/78941969-2579769454-11080025436149776384-3144993630-10057-A-0-1-imgplus.m3u8?wsSecret=9077810f34fe8d9b866ef5b9930bb232&wsTime=6017b49b&u=0&seqid=16120799213176012&ctype=tars_mobile&txyp=o%3Aq6%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&t=103'
}

**Comment by wbt5** [comment]
#157
