### ISSUE TITLE
请问你写的抓取斗鱼直播源代码，pc端 怎么获取直播源啊？

### ISSUE THREAD

**Issue by TommyLe1** [wbt5/real-url#150]
我在最后代码加了一句    print(s.get_pc_js())
但是打印出来太多乱码，虽然能手动提取出来直播源，但是有没有更简洁的方法啊？ 还是说我用错了代码了呢？
谢谢！

**Comment by TommyLe1** [comment]
查了下资料自己解决了
`        pc_url = res['data']['rtmp_url'] + '/' + res['data']['rtmp_live']
        return pc_url
`

**Comment by wbt5** [comment]
返回的是 json
