### ISSUE TITLE
抖音直播源失效

### ISSUE THREAD

**Issue by yysunq** [wbt5/real-url#164]
上午还好用呢，现在不行了。
\real-url-master (1)\real-url-master>python douyin.py
请输入抖音直播间room_id或分享链接：
https://v.douyin.com/eDm51te/
Exception： 直播间不存在或未开播或参数错误
False

**Comment by Dauth** [comment]
加 User-Agent 就可以了

**Comment by Dauth** [comment]
> 上午还好用呢，现在不行了。
> \real-url-master (1)\real-url-master>python douyin.py
> 请输入抖音直播间room_id或分享链接：
> https://v.douyin.com/eDm51te/
> Exception： 直播间不存在或未开播或参数错误
> False

请看https://github.com/wbt5/real-url/pull/165
