### ISSUE TITLE
战旗不能用了

### ISSUE THREAD

**Issue by TaoziDB** [wbt5/real-url#167]
D:\Working>python zhanqi.py
输入战旗直播房间号：
873078458
Exception： 直播间不存在
False

**Comment by wbt5** [comment]
@TaoziDB 已修复

**Comment by TaoziDB** [comment]
```cdn_host, = res.json().get('redirect_domain')```
might need to change to:
```cdn_host = res.json().get('redirect_domain')[0]```

**Comment by wbt5** [comment]
是一样的吧

**Comment by TaoziDB** [comment]
```python zhanqi.py
输入战旗直播房间号：
873078458
Exception： too many values to unpack (expected 1)
False

**Comment by wbt5** [comment]
@TaoziDB 873078458，我这能正常获取啊。难道cdn_host返回了多个值？麻烦贴出 https://umc.danuoyi.alicdn.com/dns_resolve_https?app=zqlive&host_key=alhdl-cdn.zhanqi.tv 的返回看是啥

**Comment by TaoziDB** [comment]
{"ttl":60,"redirect_domain":["ip3809932847.mobgslb.tbcache.com","ip3776509487.mobgslb.tbcache.com"]}

from USA IP

**Comment by wbt5** [comment]
@TaoziDB 十分感谢，稍后更新代码
