### ISSUE TITLE
求助，关于bili有些解析出来的无法播放

### ISSUE THREAD

**Issue by ixinshang** [wbt5/real-url#169]
测试环境：python 3.9.1
real-url 最新版
测试B站房间：839437
解析出来地址看着显示正常，但是放在播放器（测试了potplayer）里面，flv_url和hls_url都播放失败。

**Comment by wbt5** [comment]
可能与地域不同有关，待测试确定。

**Comment by ixinshang** [comment]
> 可能与地域不同有关，待测试确定。

好的 @wbt5

**Comment by wbt5** [comment]
@ixinshang 我这试着播了两个小时都正常。麻烦发下直播间和获取的地址。

**Comment by ixinshang** [comment]
@wbt5   好的谢谢  我这儿暂时没法复现这个问题。  后面遇到的话，我会提供更详细的信息
