### ISSUE TITLE
爱奇艺报错

### ISSUE THREAD

**Issue by zqs125** [wbt5/real-url#172]
你好，谢谢分享这么好的代码，我现在是在同一环境中，测试了虎牙、斗鱼没有问题，但是爱奇艺报错，无法获取到源，报错信息：
Exception： 'NoneType' object has no attribute 'get'
False

我不知道是我哪个地方没弄好，请指导下，谢谢了

**Comment by wbt5** [comment]
确定是否有js环境，或者贴出直播间

**Comment by zqs125** [comment]
斗鱼也用的execjs都没有问题，我是试不管哪个直播间都是这个错误，比如这个74429吧，我是感觉很奇怪，像是在42行就报错了

**Comment by wbt5** [comment]
@zqs125 很奇怪哦，74429 我试了，能正常获取。使用的最新代码吧

**Comment by zqs125** [comment]
嗯，是最新的，requests模块我也重装了，就这个iqiyi报错，真的是奇怪，我在42行加了个try，走到这就报异常了，想不明白

**Comment by wbt5** [comment]
@zqs125 试试把异常处理去掉，看报啥错

**Comment by SeaHOH** [comment]
也许是 DNS/CDN 的问题

**Comment by zqs125** [comment]
我测试了，67行获取的数据是try{jsonp_1621765820871_0000({"code":"A00001","msg":"rule block."});}catch(e){};这个，然后68行处理后的json是{'code': 'A00001', 'msg': 'rule block.'}，之后就是69行报这个错误了AttributeError: 'NoneType' object has no attribute 'get'

**Comment by wbt5** [comment]
@zqs125 从爱奇艺的js中得知，出现A00001是请求参数无效，可能与 @SeaHOH 说的有关，或许请求参数中有个用来判断地区的。
试试这个链接有没有正常返回：
https://live.video.iqiyi.com/jp/live?lc=&lp=8804271532322023&src=02027251010000000000&rateVers=H5_QIYI&t=1621767209906&uid=&v=0&k_ft4=1&qd_v=1&qdy=a&qds=0&tm=1621767209&vf=6dfe4035da0d1049a9cc15d769799c8e&callback=jsonp_1621767209906_5451

**Comment by zqs125** [comment]
@wbt5 试了你发的这个连接是可以，返回的数据是正确的

**Comment by wbt5** [comment]
@zqs125 尝试将 iqiyi.py 代码里 52 行 params 中的 src 改为 02037251010000000000 或 02027251010000000000，如果还不行，说明请求时可能参数不完整，等下次更新时再来补全。

**Comment by zqs125** [comment]
OK，现在已经OK了
