### ISSUE TITLE
网易的房间号为什么没规则

### ISSUE THREAD

**Issue by kjfddfjk** [wbt5/real-url#18]
这样的
http://cc.163.com/37/5599674/
这个房间号到底是什么？
http://cc.163.com/5599674/ ，转到另一个房间了
http://cc.163.com/375599674 ，房间404

还有的比如
https://h5.cc.163.com/cc/19681748
h5开头的这些是手机端分享
http://cc.163.com/22155/6199354/
这种是手机端分享复制下来电脑端出现的

**Comment by wbt5** [comment]
http://cc.163.com/37/5599674/，这种直播间链接，源码里37是room_id，5599674是channel_id，
它有个ccid：313976847，传入的是这个直播间号。

**Comment by wei168hua** [comment]
呵呵呵 这个简单啊

**Comment by kjfddfjk** [comment]
好的，感谢
