### ISSUE TITLE
斗鱼失效

### ISSUE THREAD

**Issue by xyf2018** [wbt5/real-url#184]
失效应该是在6月3号晚上发生的，下午的时候还可以正常使用。

目前运行脚本依然可以得到url，形式是http://tx2play1.douyucdn.cn/live/{key}.flv 格式。因为脚本获取的就是key，前面的域名部分是本地拼接的，所以我怀疑获取到的key依然是正确的，但是域名已经不再是这个形式了。

从浏览器抓了一下直播地址，脚本获取的key是正确的，但前面的域名部分变了，成了一个与地址及ISP相关的域名（我在长沙，用的移动网，可以在域名中看到changsha、cmcc）。而且似乎加入了验证，把域名改成浏览器抓到的，放进播放器也播放不了，http和https都不行。

浏览器抓的地址中还有像wsAuth，token等这样的参数，一并放到播放器中倒是可以播

**Comment by junlongzzz** [comment]
使用PC端或H5端的获取方式目前依旧都有效 via https://junlong.plus/ztool/live/douyu/22222
本人直接使用的返回数据内的播放链接播放，你可以F12看看我这里获取的播放链接。

**Comment by xyf2018** [comment]
> 将.flv后缀修改为.xs后缀，目前我测试可用

确实，改成xs就可以了

**Comment by xyf2018** [comment]
> 使用PC端或H5端的获取方式目前依旧都有效 via https://junlong.plus/ztool/live/douyu/22222
> 本人直接使用的返回数据内的播放链接播放，你可以F12看看我这里获取的播放链接。

的确，听你这一说，我改了下代码试着用pc端的方式获取地址，得到地址是有效的，和从你网站上得到的地址一样。
不过我改完之后，pc端方式返回的结果是json格式，我得从里面手动把地址复制出来……我不是很会python，能看看您是怎么改的吗

**Comment by xyf2018** [comment]
> > > 使用PC端或H5端的获取方式目前依旧都有效 via https://junlong.plus/ztool/live/douyu/22222
> > > 本人直接使用的返回数据内的播放链接播放，你可以F12看看我这里获取的播放链接。
> > 
> > 
> > 的确，听你这一说，我改了下代码试着用pc端的方式获取地址，得到地址是有效的，和从你网站上得到的地址一样。
> > 不过我改完之后，pc端方式返回的结果是json格式，我得从里面手动把地址复制出来……我不是很会python，能看看您是怎么改的吗
> 
> 我是用Java实现的，python也是拼接一下 via #150

感谢！

**Comment by wbt5** [comment]
Duplicate of #185
