### ISSUE TITLE
临时解决斗鱼直播源问题

### ISSUE THREAD

**Issue by gtrvirgo** [wbt5/real-url#196]
感谢本项目各位大佬的辛勤工作和无私奉献！！！
在douyu.py文件第51行，返回之前添加：
`data = res['data']`
临时解决本次更新之后斗鱼直播源失效问题

**Comment by guolei368** [comment]
怎么修改。添加在51行哪里？

**Comment by iceking2nd** [comment]
临时解决其实在douyu.py@952ed5c这个版本获取到的URL基础上，把.flv改成.xs就行。

**Comment by gtrvirgo** [comment]
啊这……回滚太重了。在最新版本douyu.py文件第51行return之前添加一行
`data = res['data']`
