### ISSUE TITLE
央视频欧洲杯直播

### ISSUE THREAD

**Issue by gyileng** [wbt5/real-url#204]
您好，欧洲杯火热进行中，是否可以解析下直播源链接，目前欧洲杯的赛事期间，网页的CCTV5停止直播，需要从央视频的手机客户端观看，不知是否可以解析。
不过爱奇艺体育也是有直播的，可以从网页端进行观看。

**Comment by wbt5** [comment]
@gyileng 央视频APP段有加固，解析难度较大，参看 #95 ，爱奇艺体育待调试添加。

**Comment by wbt5** [comment]
已添加
