### ISSUE TITLE
大佬帮忙看一下关于企鹅电竞弹幕的问题 感恩

### ISSUE THREAD

**Issue by comspalpeen** [wbt5/real-url#209]
一开始运行是这样的 能正常输出几秒弹幕 然后报错出现这个 然后我看到之前有人问过这个问题 照着下面回答的改了        ![image](https://user-images.githubusercontent.com/86298635/122919172-8382b780-d392-11eb-88bc-f04d4d6ae2a8.png)    加了一段if t == '':
              t = 0然后还是能正常输出几秒又出现了这个错误
![%1~E )V2QH6T2QEJ__7`Y}L](https://user-images.githubusercontent.com/86298635/122920244-c2fdd380-d393-11eb-9ced-e6b8c147141b.png)   大佬有时间帮忙看一下

**Comment by wbt5** [comment]
Fixed
