### ISSUE TITLE
虎牙弹幕失效了

### ISSUE THREAD

**Issue by TaoziDB** [wbt5/real-url#215]
虎牙弹幕失效了，麻烦老大修一下，谢谢

**Comment by bbllmaster** [comment]
改下正则试试https://github.com/wbt5/real-url/pull/218/commits/5e5b43d55c0df7e460e0bc359470975fda9b40ac

**Comment by TaoziDB** [comment]
谢了
> 改下正则试试[5e5b43d](https://github.com/wbt5/real-url/commit/5e5b43d55c0df7e460e0bc359470975fda9b40ac)
