### ISSUE TITLE
虎牙直播中地址 显示未开播或直播间不存在

### ISSUE THREAD

**Issue by Felrix** [wbt5/real-url#216]
https://www.huya.com/196645                              房间号196645
https://www.huya.com/zhangjiawen                      房间号181469

**Comment by BoneAsh** [comment]
请使用新版的huya.py重新解析

**Comment by Felrix** [comment]
> 请使用新版的huya.py重新解析

用的是两天前更新的huya.py
解析了有4个直播地址还是不行
