### ISSUE TITLE
ACfun弹幕获取bug

### ISSUE THREAD

**Issue by Kyokorin0** [wbt5/real-url#217]
加入守护团消息
错误日志:
AttributeError: module 'danmaku.acfun_pb2' has no attribute 'AcfunActionSignalJoinClub'
送出红包礼物消息
错误日志：
AttributeError: 'NoneType' object has no attribute 'send'

AttributeError: module 'danmaku.acfun_pb2' has no attribute 'CommonActionSignalRichText'

**Comment by wbt5** [comment]
Fixed
