### ISSUE TITLE
17直播可以获得地址 但无法播放？

### ISSUE THREAD

**Issue by coolzzzz** [wbt5/real-url#22]
mac下用iina，win用potplayer都无法播放，提示服务器已关闭或地址错误，播放器需要什么设置吗？

**Comment by wbt5** [comment]
刚才看了下，17直播官方屏蔽了大陆IP，导致获取 wansu-global-pull-rtmp.17app.co 这个域名的链接无法播放。
我在源码离添加了个新的播放链接，你可以试试。

**Comment by TaoziDB** [comment]
请输入17直播房间号：
8628084
该直播间源地址为：
['http://qiniu-global-pull-rtmp.17app.co/17app/46acd48a-fcb8-45b7-994f-890214008d36.flv', 'http://wansu-china-pull-rtmp-17.tigafocus.com/vod/46acd48a-fcb8-45b7-994f-890214008d36.flv']

如果开头是qiniu的话，两个链接都不行
从网页抓包的结果，播放所有flv的时候加了header：Referer: https://17.live/live/{livestreamid}
用livestreamid替换{livestreamid}
如果播放的时候没有加头的话，RpcError(403,/play/connect,Forbidden)

**Comment by wbt5** [comment]
> 请输入17直播房间号：
> 8628084
> 该直播间源地址为：
> ['http://qiniu-global-pull-rtmp.17app.co/17app/46acd48a-fcb8-45b7-994f-890214008d36.flv', 'http://wansu-china-pull-rtmp-17.tigafocus.com/vod/46acd48a-fcb8-45b7-994f-890214008d36.flv']
> 
> 如果开头是qiniu的话，两个链接都不行
> 从网页抓包的结果，播放所有flv的时候加了header：Referer: [https://17.live/live/{livestreamid}](https://17.live/live/%7Blivestreamid%7D)
> 用livestreamid替换{livestreamid}
> 如果播放的时候没有加头的话，RpcError(403,/play/connect,Forbidden)


这个直播间已经关播了，没法测试。
但我这边找了几个qiniu开头的，返回链接是这种：http://qiniu-china-pull-rtmp-17.tigafocus.com/17app/33ac9d69-dea1-4607-a6e2-c94880f96b48.flv，没有referer也可播放。
看样子可能域名中带global的都不能播。
待验证再更新。

**Comment by TaoziDB** [comment]
如果
https://qiniu-global-pull-rtmp.17app.co/17app/{userid}.flv
换成：
http://qiniu-china-pull-rtmp-17.tigafocus.com/17app/{userid}.flv
就可以了，和wansu类似的思路

**Comment by wbt5** [comment]
> 如果
> [https://qiniu-global-pull-rtmp.17app.co/17app/{userid}.flv](https://qiniu-global-pull-rtmp.17app.co/17app/%7Buserid%7D.flv)
> 换成：
> [http://qiniu-china-pull-rtmp-17.tigafocus.com/17app/{userid}.flv](http://qiniu-china-pull-rtmp-17.tigafocus.com/17app/%7Buserid%7D.flv)
> 就可以了，和wansu类似的思路

感谢老哥~

**Comment by wbt5** [comment]
已更新

**Comment by coolzzzz** [comment]
你好，知道17live转换后的真实地址，比如 0b5dcfde-94f2-45c6-b383-5d74ed3fb7c9，可以反推直播间号吗

**Comment by JHL2299** [comment]
同样问题求助，有偿，https换http有一秒画面然后卡死，能解决的大哥私

**Comment by JHL2299** [comment]
同样问题求助，有偿，https换http有一秒画面然后卡死，能解决的大哥私

**Comment by JHL2299** [comment]
> > 请输入17直播房间号：
> > 8628084
> > 该直播间源地址为：
> > ['http://qiniu-global-pull-rtmp.17app.co/17app/46acd48a-fcb8-45b7-994f-890214008d36.flv', 'http://wansu-china-pull-rtmp-17.tigafocus.com/vod/46acd48a-fcb8-45b7-994f-890214008d36.flv']
> > 如果开头是qiniu的话，两个链接都不行
> > 从网页抓包的结果，播放所有flv的时候加了header：Referer: [https://17.live/live/{livestreamid}](https://17.live/live/%7Blivestreamid%7D)
> > 用livestreamid替换{livestreamid}
> > 如果播放的时候没有加头的话，RpcError(403,/play/connect,Forbidden)
> 
> 这个直播间已经关播了，没法测试。 但我这边找了几个qiniu开头的，返回链接是这种：[http://qiniu-china-pull-rtmp-17.tigafocus.com/17app/33ac9d69-dea1-4607-a6e2-c94880f96b48.flv，没有referer也可播放。](http://qiniu-china-pull-rtmp-17.tigafocus.com/17app/33ac9d69-dea1-4607-a6e2-c94880f96b48.flv%EF%BC%8C%E6%B2%A1%E6%9C%89referer%E4%B9%9F%E5%8F%AF%E6%92%AD%E6%94%BE%E3%80%82) 看样子可能域名中带global的都不能播。 待验证再更新。

大哥求助求助
