### ISSUE TITLE
pip需要哪个版本啊 自动更新了pip最新版本，与你其他requirements应该不兼容

### ISSUE THREAD

**Issue by 18862005630** [wbt5/real-url#227]

**Comment by BoneAsh** [comment]
具体安装哪个包报错的，以及报错内容是什么

**Comment by 18862005630** [comment]
> 具体安装哪个包报错的，以及报错内容是什么

douyu.py文件里execjs包，下载时候会报pip版本问题，下载不了

**Comment by BoneAsh** [comment]
> > 具体安装哪个包报错的，以及报错内容是什么
> 
> douyu.py文件里execjs包，下载时候会报pip版本问题，下载不了

我这里使用的是环境是Python3.8.6 + pip21.1.3
execjs 的包名应该是PyExecJS，当前版本是1.5.1，我没遇到安装时报错的问题

**Comment by 18862005630** [comment]
> > > 具体安装哪个包报错的，以及报错内容是什么
> > 
> > 
> > douyu.py文件里execjs包，下载时候会报pip版本问题，下载不了
> 
> 我这里使用的是环境是Python3.8.6 + pip21.1.3
> execjs 的包名应该是PyExecJS，当前版本是1.5.1，我没遇到安装时报错的问题

我的环境是python3.7.4 + pip21.1.3，execjs能搜索到的版本是1.5.1，意思是我要升级python版本了？

**Comment by 18862005630** [comment]
> > > 具体安装哪个包报错的，以及报错内容是什么
> > 
> > 
> > douyu.py文件里execjs包，下载时候会报pip版本问题，下载不了
> 
> 我这里使用的是环境是Python3.8.6 + pip21.1.3
> execjs 的包名应该是PyExecJS，当前版本是1.5.1，我没遇到安装时报错的问题

我改成你那个python版本，依旧报pip版本错误，下载不了execjs

**Comment by BoneAsh** [comment]
> > > > 具体安装哪个包报错的，以及报错内容是什么
> > > 
> > > 
> > > douyu.py文件里execjs包，下载时候会报pip版本问题，下载不了
> > 
> > 
> > 我这里使用的是环境是Python3.8.6 + pip21.1.3
> > execjs 的包名应该是PyExecJS，当前版本是1.5.1，我没遇到安装时报错的问题
> 
> 我改成你那个python版本，依旧报pip版本错误，下载不了execjs

理论上跟pip版本没啥关系，因为我也用其他版本pip安装过，把所有错误日志粘贴出来呗，以及环境信息(操作系统啊之类的)，实在不行，在其他机器上安装试试，有可能是环境因素导致的

**Comment by 18862005630** [comment]
> > > > > 具体安装哪个包报错的，以及报错内容是什么
> > > > 
> > > > 
> > > > douyu.py文件里execjs包，下载时候会报pip版本问题，下载不了
> > > 
> > > 
> > > 我这里使用的是环境是Python3.8.6 + pip21.1.3
> > > execjs 的包名应该是PyExecJS，当前版本是1.5.1，我没遇到安装时报错的问题
> > 
> > 
> > 我改成你那个python版本，依旧报pip版本错误，下载不了execjs
> 
> 理论上跟pip版本没啥关系，因为我也用其他版本pip安装过，把所有错误日志粘贴出来呗，以及环境信息(操作系统啊之类的)，实在不行，在其他机器上安装试试，有可能是环境因素导致的

Try to run this command from the system terminal. Make sure that you use the correct version of 'pip' installed for your Python interpreter located at 'F:\python_ide\workspaces\allvideo\real-url\venv\Scripts\python.exe'.

**Comment by BoneAsh** [comment]
> Try to run this command from the system terminal. Make sure that you use the correct version of 'pip' installed for your Python interpreter located

报这个错一般都是使用的pip与实际使用的python对应不上，我看你的提示中python路径中有venv，说明你是使用了virtualenv创建的虚拟环境吧，那每次使用该虚拟环境之前是需要执行Scripts下的activate.bat脚本以切换至该虚拟环境的；而且如果你使用了pycharm等ide也要相应做出环境配置调整。总之，是你环境的配置问题，请检查并修正。

**Comment by sayviness** [comment]
`pip install PyExecJS`
用这个就好了

**Comment by 18862005630** [comment]
> `pip install PyExecJS`
> 用这个就好了

下载是需要特定指定下载源，并且如果用的是虚拟环境，要用py -m 命令安装，否则安装的是系统环境，安装问题解决了，但是运行斗鱼的时候报错：ValueError: check_hostname requires server_hostname

**Comment by BoneAsh** [comment]
> > `pip install PyExecJS`
> > 用这个就好了
> 
> 下载是需要特定指定下载源，并且如果用的是虚拟环境，要用py -m 命令安装，否则安装的是系统环境，安装问题解决了，但是运行斗鱼的时候报错：ValueError: check_hostname requires server_hostname

可以先检查一下电脑是否开代理了，如果开了就关代理再试试

**Comment by 18862005630** [comment]
> > > `pip install PyExecJS`
> > > 用这个就好了
> > 
> > 
> > 下载是需要特定指定下载源，并且如果用的是虚拟环境，要用py -m 命令安装，否则安装的是系统环境，安装问题解决了，但是运行斗鱼的时候报错：ValueError: check_hostname requires server_hostname
> 
> 可以先检查一下电脑是否开代理了，如果开了就关代理再试试

额。。。可以了 代理必须直接关闭软件，我改直连都不行
