### ISSUE TITLE
虎牙直播地址不能播放

### ISSUE THREAD

**Issue by guyijie1211** [wbt5/real-url#230]
我试了一下 [#221 ](https://github.com/wbt5/real-url/pull/221) 的代码好像还是不行

**Comment by BoneAsh** [comment]
请提供一下房间号及输出信息，我刚才随便解析了一个还是能用的

**Comment by BoneAsh** [comment]
> 我试了一下 [#221 ](https://github.com/wbt5/real-url/pull/221) 的代码好像还是不行

请提供一下房间号及输出信息，我刚才随便解析了一个还是能用的

**Comment by michael12610** [comment]
同上。。这样获取到的url地址，从12号开始都是access denied了，偶尔有一两个还能播放。。

**Comment by WincerChan** [comment]
http://121.12.115.101/tx.hls.huya.com/src/1394575534-1394575534-5989656310331736064-2789274524-10057-A-0-1.m3u8 这个 ip 可用

**Comment by WincerChan** [comment]
121.51.120.29 这个也可用

**Comment by guyijie1211** [comment]
> http://121.12.115.101/tx.hls.huya.com/src/1394575534-1394575534-5989656310331736064-2789274524-10057-A-0-1.m3u8 这个 ip 可用
可以了，谢谢

**Comment by guyijie1211** [comment]
> 121.51.120.29

老哥，好像都失效了，还有什么办法没

**Comment by WincerChan** [comment]
121.51.249.6 @guyijie1211
