### ISSUE TITLE
央视频有些链接无法提取

### ISSUE THREAD

**Issue by yeahjack** [wbt5/real-url#237]
提示信息为
`{'iretcode': 46, 'iretdetailcode': 0, 'errinfo': '当前节目不能试看'}`
链接为https://w.yangshipin.cn/video?type=1&vid=2000204503&pid=600001817

**Comment by wbt5** [comment]
错误信息就是里面提示的那样，这无法解决的。

**Comment by yeahjack** [comment]
> 错误信息就是里面提示的那样，这无法解决的。

所以对于网页端不提供观看的就不能抓取m3u8了是吗

**Comment by wbt5** [comment]
@yeahjack 是的。app端加固过，暂时没能力搞定，欢迎贡献其他方法。

**Comment by yeahjack** [comment]
好的，非常感谢！
