### ISSUE TITLE
请问执行了 pip install -r requirements.txt 出现错误

### ISSUE THREAD

**Issue by eternalveilangel** [wbt5/real-url#270]
![Screenshot 2021-10-01 143732](https://user-images.githubusercontent.com/61597657/135576480-ef2da6e6-1f58-4603-b6aa-f9144c85a5f5.png)

请问是哪里出错了呢

**Comment by joffeego** [comment]
好像不要用代理就好

**Comment by wbt5** [comment]
@eternalveilangel 建议重新下载安装 python，用清华源安装 pip
