### ISSUE TITLE
B站的有的可能失效

### ISSUE THREAD

**Issue by 5ME** [wbt5/real-url#303]
我浏览器装了IDM插件，打开直播间，好像是IDM浮动条显示m3u8的就能正常获取，显示flv的就不能了

比如 `764155` 直播间

**Comment by 7ongOrz** [comment]
我的这也有部分失效...

**Comment by AbsoluteMiracle** [comment]
Replace line 61 to 71 with:

```Python
        for data in stream_info:
            format_name = data['format'][0]['format_name']

            if format_name not in stream_info:
                stream_urls[format_name] = {}

            base_url = data['format'][-1]['codec'][0]['base_url']
            url_info = data['format'][-1]['codec'][0]['url_info']

            for i, info in enumerate(url_info):
                host = info['host']
                extra = info['extra']
                stream_urls[format_name][f'线路{i + 1}'] = f'{host}{base_url}{extra}'
````

This problem cause by flv stream address not work at the time of last commit.
So flv address was removed to prevent knowning problem and line 61 mentioned this.

Currently, flv stream address works in both Potplayer and VLC by my simple test.
You can make a try with the codes on top.

**Comment by 5ME** [comment]
> Replace line 61 to 71 with:
> 
> ```python
>         for data in stream_info:
>             format_name = data['format'][0]['format_name']
> 
>             if format_name not in stream_info:
>                 stream_urls[format_name] = {}
> 
>             base_url = data['format'][-1]['codec'][0]['base_url']
>             url_info = data['format'][-1]['codec'][0]['url_info']
> 
>             for i, info in enumerate(url_info):
>                 host = info['host']
>                 extra = info['extra']
>                 stream_urls[format_name][f'线路{i + 1}'] = f'{host}{base_url}{extra}'
> ```
> 
> This problem cause by flv stream address not work at the time of last commit. So flv address was removed to prevent knowning problem and line 61 mentioned this.
> 
> Currently, flv stream address works in both Potplayer and VLC by my simple test. You can have a try with the codes on top.

解决了，十分感谢
