### ISSUE TITLE
电视盒子用的

### ISSUE THREAD

**Issue by li-xiaog** [wbt5/real-url#333]
电视盒子用的，主要看直播间电影用的，大家看看能用不

https://wwn.lanzout.com/iWMlv02uexqb
密码:aui2

**Comment by dingzhengjie** [comment]
啥直播，虎牙？

**Comment by li-xiaog** [comment]
> 啥直播，虎牙？

大佬住在这了吗？ 虎牙、斗鱼、B站

**Comment by dingzhengjie** [comment]
关注了，app有推送消息

**Comment by dingzhengjie** [comment]
> > 啥直播，虎牙？
> 
> 
> 
> 大佬住在这了吗？ 虎牙、斗鱼、B站

你的斗鱼怎么获取直链的

**Comment by li-xiaog** [comment]
> > > 啥直播，虎牙？
> > 
> > 
> > 大佬住在这了吗？ 虎牙、斗鱼、B站
> 
> 关注了，app有推送消息，你的斗鱼怎么获取直链的，我的php版本获取不了，只能打印链接

我的用的 @rain-dl  的代码，主要是第一次请求的地址变了

**Comment by li-xiaog** [comment]
另外我这里这几个cdn能用 
ws-tct.douyucdn.cn
akm-tct.douyucdn.cn
hls3-akm.douyucdn.cn
hls1a-akm.douyucdn.cn

**Comment by dingzhengjie** [comment]
> > > > 啥直播，虎牙？
> > > 
> > > 
> > > 大佬住在这了吗？ 虎牙、斗鱼、B站
> > 
> > 
> > 关注了，app有推送消息，你的斗鱼怎么获取直链的，我的php版本获取不了，只能打印链接
> 
> 我的用的 @rain-dl 的代码，主要是第一次请求的地址变了

你的app虎牙看不了

**Comment by li-xiaog** [comment]
> > > > > 啥直播，虎牙？
> > > > 
> > > > 
> > > > 大佬住在这了吗？ 虎牙、斗鱼、B站
> > > 
> > > 
> > > 关注了，app有推送消息，你的斗鱼怎么获取直链的，我的php版本获取不了，只能打印链接
> > 
> > 
> > 我的用的 @rain-dl 的代码，主要是第一次请求的地址变了
> 
> 你的app虎牙看不了，app自己写的？

瞎写的   没做适配    崩了吗

**Comment by wuziyu2580** [comment]
请问大哥们为啥输入房间号后直接退了
