### ISSUE TITLE
弹幕模式就是在终端里面显示的吗？

### ISSUE THREAD

**Issue by antizo** [wbt5/real-url#34]
满满的割裂感啊

**Comment by wbt5** [comment]
> 满满的割裂感啊

目前弹幕仅实现打印，展示方式以后再折腾😋

**Comment by antizo** [comment]
> > 满满的割裂感啊
> 
> 目前弹幕仅实现打印，展示方式以后再折腾yum

这个类似的，实现了弹幕视频整合：https://github.com/IsoaSFlus/QLivePlayer
