### ISSUE TITLE
运行douyu.py提示 "ImportError: No module named execjs"

### ISSUE THREAD

**Issue by CnTripto** [wbt5/real-url#387]
实际已经完成安装requirements.txt里的所有依赖包
并且执行pip list结果显示存在PyExecJS包
`
Package                Version
---------------------- --------------------
aiohttp                3.7.4
async-timeout          3.0.1
attrs                  20.2.0
cached-property        1.5.1
certifi                2020.6.20
chardet                3.0.4
charset-normalizer     2.0.12
cloud-init             19.1.11
command-not-found      0.3
configobj              5.0.6
dbus-python            1.2.16
distro                 1.4.0
distro-info            0.23ubuntu1
docker                 4.1.0
docker-compose         1.25.0
dockerpty              0.4.1
docopt                 0.6.2
idna                   2.10
importlib-metadata     1.5.0
importlib-resources    5.4.0
iotop                  0.6
Jinja2                 3.0.3
jsonpatch              1.32
jsonpointer            2.2
jsonschema             4.2.1
language-selector      0.1
MarkupSafe             2.0.1
more-itertools         4.2.0
multidict              4.7.6
netifaces              0.10.4
oauthlib               3.1.1
pip                    20.0.2
protobuf               3.12.2
pycryptodome           3.9.8
PyExecJS               1.5.1
PyGObject              3.36.0
pymacaroons            0.13.0
PyNaCl                 1.3.0
pyrsistent             0.18.0
python-apt             2.0.0+ubuntu0.20.4.6
PyYAML                 6.0
requests               2.26.0
setuptools             65.3.0
six                    1.16.0
ssh-import-id          5.10
texttable              1.6.2
typing-extensions      3.7.4.3
ubuntu-advantage-tools 27.4
ufw                    0.36
urllib3                1.26.5
websocket-client       0.53.0
wheel                  0.34.2
yarl                   1.5.1
zipp                   3.6.0
`

**Comment by TheDDF6** [comment]
同，我也想问
