### ISSUE TITLE
抖音解析结果 [ffmpeg] http: HTTP error 404 Not Found

### ISSUE THREAD

**Issue by Ch1cC** [wbt5/real-url#391]
使用播放器mpv执行解析结果的url失败,确认是开播状态

**Comment by iWorkers** [comment]
> 使用播放器mpv执行解析结果的url失败,确认是开播状态
> 
> 

我修改了一下可以正常解析

**Comment by Ch1cC** [comment]
> > 使用播放器mpv执行解析结果的url失败,确认是开播状态
> 
> 我修改了一下可以正常解析

是什么思路呢,我播放器ua也改了,程序解析的url访问就是404

**Comment by iWorkers** [comment]
拿到19位room_id> > > 使用播放器mpv执行解析结果的url失败,确认是开播状态
> 
> > 
> 
> > 我修改了一下可以正常解析
> 
> 
> 
> 是什么思路呢,我播放器ua也改了,程序解析的url访问就是404


拿到19位room_id就可以了

**Comment by Ch1cC** [comment]
> 拿到19位room_id> > > 使用播放器mpv执行解析结果的url失败,确认是开播状态
> 
> > > 
> > 
> > 
> > > 我修改了一下可以正常解析
> > 
> > 
> > 是什么思路呢,我播放器ua也改了,程序解析的url访问就是404
> 
> 拿到19位room_id就可以了

昨天突然能用了
