### ISSUE TITLE
作者大大可以研究一下斗鱼的HTTPS直播流吗？

### ISSUE THREAD

**Issue by qianjiachun** [wbt5/real-url#4]
目前只有http的直播流，虽然改成https也可以，但是有证书过期的问题。
希望可以研究一下https://www.douyu.com/lapi/live/getH5Play/<rid>中sign值的获取方法。
这个接口是返回https直播流地址的
非常感谢

**Comment by lighterEB** [comment]
楼上的兄弟没有看懂代码吧，斗鱼真实地址其实就是tx2开头的加上房间号和后面的随机字符再加上.flv后缀，所以说基本思路是提取房间号加后面的随机字符就好了

**Comment by qianjiachun** [comment]
> 楼上的兄弟没有看懂代码吧，斗鱼真实地址其实就是tx2开头的加上房间号和后面的随机字符再加上.flv后缀，所以说基本思路是提取房间号加后面的随机字符就好了

确实是这样。但是我目前是在https下使用flv.js来做画中画的功能。这种情况下目前生成的http地址并不能直接用于播放，必须也得是https才行。

虽然将http直接改成https也可行，但是会有证书过期的提示，并不完美。

**Comment by wbt5** [comment]
> 目前只有http的直播流，虽然改成https也可以，但是有证书过期的问题。
> 希望可以研究一下https://www.douyu.com/lapi/live/getH5Play/中sign值的获取方法。
> 这个接口是返回https直播流地址的
> 非常感谢

感谢支持，等有空了再研究一下。因为之前一直是放在potplayer中本地播放的，没注意过这个问题。

**Comment by qianjiachun** [comment]
嗯嗯感谢回复。我是将地址用于flv.js内播放来达到画中画的功能的，目前为止您的方法还是勉强可用的。感激不尽




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"乌帮图"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月24日(星期一) 晚上10:58
收件人:&nbsp;"wbt5/real-url"<real-url@noreply.github.com&gt;;
抄送:&nbsp;"小淳"<189964430@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wbt5/real-url] 作者大大可以研究一下斗鱼的HTTPS直播流吗？ (#4)



 
目前只有http的直播流，虽然改成https也可以，但是有证书过期的问题。
 希望可以研究一下https://www.douyu.com/lapi/live/getH5Play/中sign值的获取方法。
 这个接口是返回https直播流地址的
 非常感谢
  
感谢支持，等有空了再研究一下。因为之前一直是放在potplayer中本地播放的，没注意过这个问题。

**Comment by qianjiachun** [comment]
> 有解决办法了么，我在https站点上播放时，因为斗鱼url是http协议的地址所以被拦截了。

https://github.com/qianjiachun/douyuEx
已经实现

**Comment by guyijie1211** [comment]
> > 有解决办法了么，我在https站点上播放时，因为斗鱼url是http协议的地址所以被拦截了。
> 
> https://github.com/qianjiachun/douyuEx
> 已经实现
十分感谢，问题解决了

**Comment by guyijie1211** [comment]
@wbt5 
这个函数获取的https地址是否没法转换成.m3u8格式
get_js() 函数里是吧获取到的地址中flv直接换成m3u8
https连接好像要进行验证，没法直接换了

**Comment by wbt5** [comment]
@guyijie1211 试试这个 get_pre 函数返回的是 https 的 m3u8，不过不是所有直播间都有这个预览权限。
