### ISSUE TITLE
韩国afreeca TV直播可以解析？

### ISSUE THREAD

**Issue by lipinghao1986** [wbt5/real-url#41]
http://www.afreecatv.com/
只要可以解析，用翻墙什么的也没关系！

**Comment by wbt5** [comment]
我这打不开这个网站哦。

**Comment by lipinghao1986** [comment]
翻墙、VPN可以打开！还有，YY直播能修复一下？有些直播有蓝光画质的，但解析出来的只有480p




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "乌帮图"<notifications@github.com&gt;; 
发送时间: 2020年7月5日(星期天) 上午10:02
收件人: "wbt5/real-url"<real-url@noreply.github.com&gt;; 
抄送: "一只死クモ"<971737723@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wbt5/real-url] 韩国afreeca TV直播可以解析？ (#41)





 
我这打不开这个网站哦。

**Comment by liuguang2016** [comment]
我也在解析这个，没进展啊
