### ISSUE TITLE
关于抖音4K VR直播源以及YouTube稳定获取！

### ISSUE THREAD

**Issue by youshandefeiyang** [wbt5/real-url#425]
我现在用的老接口，目前抖音VR还可以获取，最高应该是3840x3840正方形分辨率，至于8000x4000的分辨率我没有见到，YouTube可指定画质加了缓存，可以参考一下下面的IPTV项目，包含各大平台直播和IPTV直播:
https://github.com/youshandefeiyang/IPTV

PS:现在可以获取8K分辨率了

**Comment by ghost** [comment]
看情况，180和360 3D最高根本就不是8K，至于3840那是因为抖音把3D双目的画面给切开了，手机端只能看单目画面给拉伸开的。直播伴侣推的是5120x5120，这一点在直播伴侣可以看到

**Comment by ghost** [comment]
你用哪个老接口获取的？我找了好多软件都没法录，只有个小绿点还是收费的。。。

**Comment by youshandefeiyang** [comment]
我自己用的接口，自己写的Go代理，目前抖音直播这块覆盖了PC和移动端都可以拿到数据

**Comment by diguawl** [comment]
> 我现在用的老接口，目前抖音VR还可以获取，最高应该是3840x3840的分辨率，至于8000x4000的分辨率我没有见到，YouTube可指定画质加了缓存，可以参考下面的IPTV项目，包含两大平台直播和IPTV直播： https://github.com/youshandefeiyang/IPTV
> 
> PS:现在可以获取8K解析了

您好，现在还可以吗，可以分享一下吗  非常感谢，可以付费！！！
