### ISSUE TITLE
有关企鹅电竞弹幕的问题

### ISSUE THREAD

**Issue by a1696585** [wbt5/real-url#47]
尊敬的作者您好
我刚试了一下企鹅电竞的弹幕，因为我只想试企鹅电竞的弹幕，所以我在_init_.py文件中，注释掉了其他内容。
运行的时候只显示如下:
{m["name"]}：s{m["content"]}
{m["name"]}：s{m["content"]}
{m["name"]}：s{m["content"]}
{m["name"]}：s{m["content"]}
{m["name"]}：s{m["content"]}
{m["name"]}：s{m["content"]}
不知道是什么情况呀。望得到您得指点，十分感谢

**Comment by wbt5** [comment]
不确定您注释掉了哪些代码，是否修改过main.py文件，理论上不会打印出类似信息。
刚测试企鹅电竞弹幕正常获取，可贴出具体的房间号来测试下。

**Comment by a1696585** [comment]
您那测试没问题的话，那估计还是我修改了部分文件导致。我改了_init_.py文件中的代码，原来是如下:
        for u, s in {'douyu.com': Douyu,
                     'live.bilibili.com': Bilibili,
                     'huya.com': Huya,
                     'huomao.com': HuoMao,
                     'kuaishou.com': KuaiShou,
                     'egame.qq.com': eGame,
                     'huajiao.com': HuaJiao,
                     'inke.cn': Inke,
                     'cc.163.com': CC}.items():
因为我其他的网站还需要导入一些包，我就想着不看这些网站是不是也行，于是我就把其他网站都删了，改成如下:
for u, s in {'egame.qq.com': eGame}.items():
其他的地方没有改动。我看了init.py里的代码，感觉我这些改动应该不会出问题呀。我再重新下载一下试试，看试不试之前改过哪给忘了

**Comment by a1696585** [comment]
新补充一下，我这次什么都没改，试了下斗鱼和B站的，都没问题。老铁很是给力。
但是试企鹅电竞的时候出现了如下的错误:
`H:\Anaconda3\python.exe H:/real-url-master/danmu/main.py
请输入直播间地址：
https://egame.qq.com/383204988
Traceback (most recent call last):
  File "H:/real-url-master/danmu/main.py", line 24, in <module>
    asyncio.run(main(a))
  File "H:\Anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "H:\Anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "H:/real-url-master/danmu/main.py", line 20, in main
    await dmc.start()
  File "H:\real-url-master\danmu\danmaku\__init__.py", line 118, in start
    self.fetch_danmaku(),
  File "H:\real-url-master\danmu\danmaku\__init__.py", line 72, in heartbeats
    while not self.__stop and self.__site.heartbeat:
AttributeError: type object 'eGame' has no attribute 'heartbeat'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000000004DA7EC8>

Process finished with exit code 1

如果您那边运行没问题，我这边运行确出错的，难道和网络有关？
`

**Comment by wbt5** [comment]
将egame.py里的heartbeats改为heartbeat。
是我代码的问题。

**Comment by wbt5** [comment]
感谢提醒，是heartbeat变量名写错了。
建议clone最新代码。

**Comment by a1696585** [comment]
嗯嗯，现在一切正常了，十分感谢。
