### ISSUE TITLE
斗鱼真实地址不用加uuid也可以播放

### ISSUE THREAD

**Issue by lighterEB** [wbt5/real-url#5]

**Comment by lighterEB** [comment]
h5preview的api请求不需要每次都计算，只要更换请求url的rid就可以了

**Comment by lighterEB** [comment]
感谢提供sign的算法

**Comment by wbt5** [comment]
> h5preview的api请求不需要每次都计算，只要更换请求url的rid就可以了

感谢提醒，稍后再优化下。
