### ISSUE TITLE
虎牙第二条链接无法播放

### ISSUE THREAD

**Issue by a936919** [wbt5/real-url#61]
第一条不是最高画质
第二条无法播放

**Comment by wbt5** [comment]
麻烦发个房间号我来试试

**Comment by lppsuixn** [comment]
@wbt5 11342412 比如这个，主要是一起看

**Comment by a936919** [comment]
@wbt5 我这里测试 全部房间第二条链接都无法播放 你可以测试一下房间号lpl

**Comment by wbt5** [comment]
@lppsuixn 一起看频道的很多直播间都会有播放问题，目前俺还没找到解决办法。有大佬会弄的可以指导一哈。

@a936919 我这测试lpl的第二条链接可以正常播放啊
