### ISSUE TITLE
大佬 ~！获取斗鱼直播源报错。。麻烦了

### ISSUE THREAD

**Issue by msjmsj** [wbt5/real-url#63]
raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='playweb.douyucdn.cn', port=443): Max retries exceeded with url: /lapi/live/hlsH5Preview/823540 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000022C55287B48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

Process finished with exit code 1

**Comment by wbt5** [comment]
这个异常应该是本地网络问题哦

**Comment by msjmsj** [comment]
本地网络...谢谢大佬回复

**Comment by msjmsj** [comment]
哇..解决了..我本地代理被修改了 谢谢
