### ISSUE TITLE
快手的直播流和弹幕都不能用了

### ISSUE THREAD

**Issue by TaoziDB** [wbt5/real-url#76]
麻烦老大看看，谢谢

**Comment by wbt5** [comment]
@TaoziDB 快手需要在headers中添加有效的cookie

**Comment by yannick1987** [comment]
请问有效的cookie是什么

**Comment by yelululiu** [comment]
> @TaoziDB 快手需要在headers中添加有效的cookie

我把浏览器中的cookie（_did=xxx; did=xxx; userId=xxx; Hm_lvt_cdce8cda34e84469b1c8015204129522=xxx; Hm_lpvt_cdce8cda34e84469b1c8015204129522=xxx; WEBLOGGER_INCREAMENT_ID_KEY=xxx; WEBLOGGER_HTTP_SEQ_ID=xxx）都copy到headers里面了，还是抛了'找不到 wsFeedInfo，可能链接错误或 Cookie 过期'，请问还需要操作什么吗？

**Comment by wbt5** [comment]
@yannick1987 使用移动网页版，类似 https://m.gifshow.com/fw/live/Yi6666666 这样，可正常播放的直播间链接中的cookie
