### ISSUE TITLE
虎牙直播流今天出问题了

### ISSUE THREAD

**Issue by TaoziDB** [wbt5/real-url#81]
大部分直播流只有包含migu-bd.hls.huya.com/src的才能播放，别的线路要么不能播，要么秒断
例如：
>python huya.py
输入虎牙直播房间号：
kpl
{'2000p': 'https://tx.hls.huya.com/src/78941969-2592787562-11135937784265572352-2914030356-10057-A-0-1-imgplus_2000.m3u8?wsSecret=cf275f8a7ec8ec4a7cd9483f60d15a51&wsTime=5f6d5fe7&u=0&seqid=16009171019629068&ctype=tars_mobile&txyp=o%3Aq6%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103', 'BD': 'https://tx.hls.huya.com/src/78941969-2592787562-11135937784265572352-2914030356-10057-A-0-1-imgplus.m3u8?wsSecret=5e2a1874dcfdc6da0d269ea196405549&wsTime=5f6d5fe7&u=0&seqid=16009171019629068&ctype=tars_mobile&txyp=o%3Aq6%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103'}

>python huya.py
输入虎牙直播房间号：
11342412
{'2000p': 'https://tx.hls.huya.com/src/94525224-2460685313-10568562945082523648-2789274524-10057-A-0-1-imgplus_2000.m3u8?wsSecret=299effa3c8632202683623d229a14177&wsTime=5f6d6070&u=0&seqid=16009172325977452&ctype=tars_mobile&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103', 'BD': 'https://tx.hls.huya.com/src/94525224-2460685313-10568562945082523648-2789274524-10057-A-0-1-imgplus.m3u8?wsSecret=ba28e2d362e008139c262fb8e964ca8e&wsTime=5f6d6070&u=0&seqid=16009172325977452&ctype=tars_mobile&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103'}

**Comment by q448159774** [comment]
现在有解决方法了？？

**Comment by wbt5** [comment]
@q448159774 试试修改url中的 tx 为 bd 或 migu-bd

**Comment by q448159774** [comment]
> @q448159774 试试修改url中的 tx 为 bd 或 migu-bd

多谢
