### ISSUE TITLE
虎牙直播流又出问题了

### ISSUE THREAD

**Issue by TaoziDB** [wbt5/real-url#85]
直播流要么不能播，要么秒断，替换 bd 或 migu-bd也不行
例如：

> python huya.py
输入虎牙直播房间号：
11342412
{'2000p': 'https://tx.hls.huya.com/src/94525224-2460685313-10568562945082523648-2789274524-10057-A-0-1-imgplus_2000.m3u8?wsSecret=30131cfa6d22b1df6073bd7a51861e0c&wsTime=5f82f749&u=0&seqid=16023321316662936&ctype=tars_mobile&txyp=o%3An4%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103', 'tx': 'https://tx.hls.huya.com/src/94525224-2460685313-10568562945082523648-2789274524-10057-A-0-1-imgplus.m3u8?wsSecret=14349f411340fecbec2903d6b7208e21&wsTime=5f82f749&u=0&seqid=16023321316662936&ctype=tars_mobile&txyp=o%3An4%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103', 'bd': 'https://bd.hls.huya.com/src/94525224-2460685313-10568562945082523648-2789274524-10057-A-0-1-imgplus.m3u8?wsSecret=14349f411340fecbec2903d6b7208e21&wsTime=5f82f749&u=0&seqid=16023321316662936&ctype=tars_mobile&txyp=o%3An4%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103', 'migu-bd': 'https://migu-bd.hls.huya.com/src/94525224-2460685313-10568562945082523648-2789274524-10057-A-0-1-imgplus.m3u8?wsSecret=14349f411340fecbec2903d6b7208e21&wsTime=5f82f749&u=0&seqid=16023321316662936&ctype=tars_mobile&txyp=o%3An4%3B&fs=bgct&&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*&t=103'}

**Comment by wbt5** [comment]
@TaoziDB 估计不同地域有区别，我这测试 migu-bd 还算正常，连续播了一个多小时。
