### ISSUE TITLE
look直播找不到原视频地址

### ISSUE THREAD

**Issue by yuanye321** [wbt5/real-url#87]
look.py中的`real_url = re.findall(r'"liveUrl":([\s\S]*),"liveType"', response)[0]`这行代码匹配不到地址了，用chrome分析后发现网页中只有`<video class="u-lvp-player" src="blob:https://iplay.163.com/855def66-323c-4b40-909d-a627afdfc0aa"></video>`，仍然找不到原地址

**Comment by owlwang** [comment]
可以尝试一下我刚才提交的这个, 如果想让速度快一点可以固定住加密后的request data。

**Comment by yuanye321** [comment]
可以用了，多谢

**Comment by wbt5** [comment]
现在look直播也用了网易 asrsea 加密函数
