### ISSUE TITLE
添加身份验证伪装成已登录状态

### ISSUE THREAD

**Issue by dreamzong** [wbt5/real-url#90]
### 能否考虑对提取的直播源加入身份验证，伪装成是已登录用户在观看直播。
**虎牙似乎会对观看平台进行校验，我使用提取的直播源观看，每隔一段时间就会断流，但重新打开直播源又可以继续播放。**

**使用浏览器平台观看时如果未登录的话，过一段时间不是就会出现一个由于未登录所以画质降低的提示窗口出现嘛，思考可能是由于虎牙添加了类似身份验证的检测机制？斗鱼貌似没有这个问题。**

**所以能否实现添加带有身份验证如cookies的功能。对这方面机制不是很清楚，如果原本已考虑过但无法实现或者不是这个原因导致断流现象的出现还请谅解！**

──更新──

**今晚无法重现该问题了！看来应该是其他原因导致的，抱歉，还请删除issue。**

**Comment by wbt5** [comment]
应该不是身份验证的问题哈，以前有老哥也试过的。
如果有其他解决办法，欢迎PR代码🙏
