### ISSUE TITLE
电视直播

### ISSUE THREAD

**Issue by li-xiaog** [wbt5/real-url#95]
悄咪咪的问一句：大佬能实现抓取央视频的电视直播吗。。。

**Comment by wbt5** [comment]
@lijiaxiaoge 这个可以有，敬请期待。

**Comment by lijiaxiaoge** [comment]
那就等着大佬出手了

**Comment by panda-mute** [comment]
支持大佬，把ckey8.1搞定

**Comment by li-xiaog** [comment]
@wbt5 大佬，有实现的可能吗？？？

**Comment by wbt5** [comment]
- 需要替换 headers 中登陆的 cookie
- 目前网页版链接有效时间很短，且每个IP每天的请求数量有限制
- APP版本的链接放时间更长，但需要反编译获取ckey生成方式，以后再更新。

**Comment by li-xiaog** [comment]
大佬，不着急
