### ISSUE TITLE
不会python

### ISSUE THREAD

**Issue by Water-blue7** [wbt5/real-url#97]
不会用啊，我在python3.8运行就是一直提示我no module named "XX"，我就一直手动添加文件
![image](https://user-images.githubusercontent.com/60252035/96407623-6058a480-1214-11eb-9ee1-a57334f3002a.png)
，而且在pycharm里import报错，不能自动导包是么，有没有视频教程教一下怎么才能运行起来啊

**Comment by tl3821** [comment]
先在pc的terminal里pip install -r requirements.txt

**Comment by wangziqiang01** [comment]
虎牙有很多房间打不开了

**Comment by wangziqiang01** [comment]
> 先在pc的terminal里pip install -r requirements.txt

能成功运行了，哔哩哔哩的倒是能打开，但是清晰度不是最佳，能不能自动选择最佳画质，斗鱼也有好多房间打不开了

**Comment by wangziqiang01** [comment]
> 先在pc的terminal里pip install -r requirements.txt

而且有的地址不能在vlc中打开，但是能在potplayer里打开

**Comment by wangziqiang01** [comment]
> 先在pc的terminal里pip install -r requirements.txt

总之，很感谢你的这个脚本，谢谢，能不能做成网页端，这样在一台电脑运行你这个代码就行了，这样更多的小伙伴就能方便快捷的使用你的作品了，如果运行需要成本你还可以通过网页版收费

**Comment by wbt5** [comment]
@wangziqiang01 这个脚本主要是为大家提供一个思路，网页版的以后会再弄。52pojie 上有一些基于这个开发的现成播放工具，可以去搜搜。

**Comment by s282730788** [comment]
那个工具就是我写的【滑稽】
https://www.52pojie.cn/thread-1277856-1-1.html
